name: Artifact Upload Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [ubuntu-latest, self-hosted]

    steps:
      - name: Create a dummy file
        run: |
          mkdir -p results
          echo "<h1>Hello World</h1>" > results/report.html

      - name: Upload dummy artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: results/report.html
